[WIP] Add xfile_mode
xtensor-stack/xtensor-io pull request #105
Opened 2020-10-21 09:42 UTC by davidbrochart

Closes #95

2020-10-21 16:21 UTC, davidbrochart commented
A stored chunked array throws an exception when it has a file mode of `init`, because it doesn't make sense. Indeed, an `xfile_array` in the chunk pool is constantly mapped to a different file, so we would have to keep track of every chunk that has been visited (and thus initialized). In this case it is better to just fill the stored chunked array with a value. The natural file mode for a stored chunked array is `init_on_fail` (as in Zarr). But a value of `load` can also be used, if we want to make sure all the accessed chunks already exist in the store.
On the other hand, an individual `xfile_array` can perfectly have an `init` file mode, and in this case it will be initialized with a given value at first read access, after which its file mode changes to `load`.

2020-10-22 08:48 UTC, JohanMabille commented
I'm not sure that we want to propagate the file mode to `xhcunked_array`, especially if only one mode is valide. Besides, filling the entire chunk array on init is super costly and useless in the case of an construction from another expression.

2020-10-22 09:00 UTC, davidbrochart commented
I agree with that, I will change the stored chunked array creation so that it uses the `init_on_fail` mode.

2020-10-23 08:41 UTC, JohanMabille requested changes

2020-10-23 08:41 UTC, JohanMabille commented on include/xtensor-io/xfile_array.hpp
> +    enum xfile_mode { load, init, init_on_fail };
`enum class` would be better to avoid accidental implicit conversions.

2020-10-23 08:41 UTC, JohanMabille commented on include/xtensor-io/xfile_array.hpp
> +        xfile_array_container(const std::string& path, xfile_mode mode=load, value_type init_value=value_type());
I still don't get the need for an initial value. Initializing with garbage is fine and consistent with in-memory containers of xtensor.

2020-10-23 08:41 UTC, JohanMabille commented on include/xtensor-io/xfile_array.hpp
> +        xfile_array_container(const xexpression<OE>& e, const std::string& path, xfile_mode mode=load, value_type init_value=value_type());
Passing an `init_value` does not really make sense here since the expression will be initialized from `e`.

2020-10-23 08:41 UTC, JohanMabille commented on include/xtensor-io/xfile_array.hpp
> +            }
I think this initialization can be removed.

2020-10-26 04:23 UTC, JohanMabille approved these changes

2020-10-26 04:24 UTC, merged