Handle endianness
xtensor-stack/xtensor-io pull request #84
Opened 2020-09-21 08:28 UTC by davidbrochart

2020-09-21 09:26 UTC, JohanMabille requested changes

2020-09-21 09:26 UTC, JohanMabille commented on include/xtensor-io/xio_binary.hpp
> +                char* swapped_buffer = new char[size * sizeof(value_type)];
Please use `std::vector<char>` instead, it manages the memory for you and avoids memory leak if an exception is thrown.

2020-09-21 09:26 UTC, JohanMabille commented on include/xtensor-io/xio_binary.hpp
> +        }
This couls be simplified in
```cpp
tempate <class T>
void swap_endianness(xt::svector<T>& buffer)
{
    char* buf = reinterpret_cast<char*>(buffer.data());
    char* end  = buf + buffer.size() * sizeof(T);
    while(buf != end)
    {
        std::reverse(buf, buf + sizeof(T));
        buf += sizeof(T);
    }
```

2020-09-21 09:26 UTC, JohanMabille commented on include/xtensor-io/xio_binary.hpp
> +                swap_endianness<T>(buffer, buffer, size);
With the simplification of `swap_endianness` this simplifies into:
```cpp
swap_endianness(uncompressed_buffer);
```

2020-09-21 09:59 UTC, davidbrochart commented
Thanks for the review @JohanMabille, I will take your comments into account.
First I'd like to discuss if it's the right place to handle endianness - in the load/dump functions of each storage formats. The drawback is that each of them has to support endianness.
On the other hand, we can't just have a general function that swaps endianness of an array data, because e.g. in `xfile_array` we don't have control over when the array is loaded or dumped. But we could imagine having a callback before dumping and after loading?

2020-09-22 07:38 UTC, davidbrochart commented on include/xtensor-io/xio_binary.hpp
> +        }
Great simplification!

2020-09-22 07:43 UTC, davidbrochart commented
@JohanMabille If you think it's fine, I will make the change to `xblosc` and `xgzip` also.

2020-09-22 12:39 UTC, JohanMabille approved these changes

2020-09-22 12:41 UTC, JohanMabille commented
I think it's the right place to handle endianness. However, the `as_big_endian` parameter could be defaulted to `is_big_endian` so that formats that don't want to handle endianness don't have to do so.

2020-09-22 12:52 UTC, davidbrochart commented
Good point.
Should we move `is_big_endian()` and `swap_endianness()` to `xtensor-io.hpp`, so that it's available to every format?

2020-09-22 13:25 UTC, JohanMabille commented
I don't think so, endianness is relevant to binary formats only.

2020-09-22 13:30 UTC, davidbrochart commented
So `xblosc` and `xgzip` will need it, right?

2020-09-22 13:33 UTC, JohanMabille commented
Ah my bad, I thought `xio_binary.hpp` was included in other files as a basic buiding block. Therefore, indeed it would make sense ot move the functions ton `xtensor_io.hpp`, sorry for the confusion!

2020-09-24 06:59 UTC, merged